# Generated by Django 4.2.11 on 2024-04-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название фичи', max_length=25, verbose_name='Название фичи')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=25, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(verbose_name='Содержимое баннера')),
                ('is_active', models.BooleanField(default=True, help_text='Флаг активности баннера', verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания баннера')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления баннера')),
                ('feature_id', models.ForeignKey(help_text='Введите название бане', on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='banners_api.feature', verbose_name='Название')),
                ('tag_ids', models.ManyToManyField(help_text='Выберите теги пользователя', related_name='tags', to='banners_api.tag', verbose_name='Тэг пользователя')),
            ],
        ),
    ]
