version: '3.10'
services:
  postgres:
    image: 'postgres:latest'
    networks:
      - jopa
    environment:
      - POSTGRES_USER=banners
      - POSTGRES_PASSWORD=bulbasumkin
      - POSTGRES_DB=banners_db
    ports:
      - "5432:5432"
    labels:
      description: "Postgresql Database"
      service: "postgresql"

  web:
    container_name: banners_api
    networks:
      - jopa
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  jopa:
    driver: bridge
volumes:
  postgres: