# FROM ubuntu:latest
FROM python:3.10
LABEL authors="dglaz"

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD python manage.py runserver 0.0.0.0:8000

